print("*******************************************************************************************************************************************")
print("Hello, welcome to MadLibs! As we all know, MadLibs has been around for many years now, and has a bunch of different themes and stories.")
print("The story of the day is: ' The Three Wacky Poems', and the first poem is a love poem \n")
color = input("Enter a color: ")
pluralNoun = input("Enter a plural noun: ")
celebrity = input("Enter a celebrity: ")
print("\n")
print("Roses are", color + " "
      + "," + " " + pluralNoun + " are blue" + "." +"\n" + "I love", celebrity
      + "," + " " + "and I love you.")
print("The next poem is an acrostic about rock music. \n")
r = input("Enter an adjective starting with a R ")
o = input("Enter an adjective starting with a O ")
c = input("Enter an adjective starting with a C ")
k = input("Enter an adjective starting with a K ")
print("\n")
print("ROCK:" + " " + r,o,c,k)
print("The last poem is a limeric \n")
adjectiveLim= input("Enter an adjective: ")
nounLim= input("Enter a noun: ")
nameLim= input("Enter a person's name (simple): ")
verbLim= input("Enter a verb: ")
nounRhymeLim= input("Enter a noun rhyming with the person's name: ")
nounTwoLim= input("Enter a noun: ")
nounTwoRhymeLim= input("Enter a noun rhyming with the previous noun: ")
print("\n")
print("There once was a", adjectiveLim + " " + nounLim + " " + "named", nameLim + "." + "\n"  + "Who" , verbLim + " " + "with a banjo and" ,
      nounRhymeLim + "." + "\n" + "Three pennies and a",nounTwoLim + "." +"\n" + "Four jewels and a ",nounTwoRhymeLim + "." + "\n" +
      "More money and treasure for", nameLim)
print("*******************************************************************************************************************************************")
